---
- name: Deploy cyrus.conf basic backend configuration
  copy: src={{ item }} dest=/etc/cyrus_conf.d/{{ item }} mode=0644
  with_items:
   - 01-IDLE_cyrus.conf
   - 11-IMAP_cyrus.conf
   - 13-SIEVE_cyrus.conf
   - 15-LMTPREMOTE_cyrus.conf
   - 21-EVENTS_cyrus.conf
  notify:
    - Merge cyrus.conf configuration files
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  tags: cyrus-backend

- name: Deploy cyrus.conf LMTP backend configuration
  template: >
      src=14-LMTPUNIX_cyrus.conf
      dest=/etc/cyrus_conf.d/14-LMTPUNIX_cyrus.conf
      mode=0644
  notify:
    - Merge cyrus.conf configuration files
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  tags: cyrus-backend

- name: Deploy cyrus.conf MUPDATE backend configuration
  copy: src={{ item }} dest=/etc/cyrus_conf.d/{{ item }} mode=0644
  with_items:
   - 02-MUPDATE_cyrus.conf
  notify:
    - Merge cyrus.conf configuration files
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  when: mupdate_server == inventory_hostname
  tags: cyrus-backend

- name: Deploy cyrus.conf POP backend configuration
  copy: src={{ item }} dest=/etc/cyrus_conf.d/{{ item }} mode=0644
  with_items:
   - 12-POP_cyrus.conf
  notify:
    - Merge cyrus.conf configuration files
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  when: enable_pop != "no"
  tags: cyrus-backend

- name: Deploy cyrus.conf IMAPS backend configuration
  copy: src={{ item }} dest=/etc/cyrus_conf.d/{{ item }} mode=0644
  with_items:
   - 16-IMAPS_cyrus.conf
  notify:
    - Merge cyrus.conf configuration files
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  when: enable_legacy_ssl != "no"
  tags: cyrus-backend

- name: Deploy cyrus.conf POPS backend configuration
  copy: src={{ item }} dest=/etc/cyrus_conf.d/{{ item }} mode=0644
  with_items:
   - 17-POPS_cyrus.conf
  notify:
    - Merge cyrus.conf configuration files
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  when: enable_pop != "no" and enable_legacy_ssl != "no"
  tags: cyrus-backend
