---
- name: Edit /etc/hosts file
  lineinfile: >
    dest=/etc/hosts
    insertafter="^127\.0\.0\.1"
    line="{{ item }}"
  when: update_host == "yes"
  with_items:
   - "{{ ldap_record }}"
   - "{{ back_record }}"
   - "{{ front_record }}"
   - "{{ murder_record }}"
  tags: cyrus-common
