---
- include: include_vars.yml
- include: hosts.yml
- include: packages.yml
- include: services.yml
  when: ansible_distribution == "Debian"
- include: pam.yml
- include: config.yml
- include: flush.yml
