---
- name: Add missing mupdate service in /etc/services
  lineinfile: >
      dest=/etc/services
      insertafter="^svn.*3690.*"
      line="mupdate         3905/tcp                        # Cyrus imap synchronization service"
  notify:
    - Restart Cyrus-Imapd service
  tags: cyrus-common

- name: Add missing sieve service in /etc/services
  lineinfile: >
      dest=/etc/services
      insertafter="^sieve.*4190.*"
      line="sieve           4190/tcp                        # Cyrus imap mail filtering service"
  notify:
    - Restart Cyrus-Imapd service
  tags: cyrus-common

- name: Add missing lmtp service in /etc/services
  lineinfile: >
      dest=/etc/services
      insertafter="^lmtp.*24.*"
      line="lmtp            24/tcp                          # Cyrus imap mail filtering service"
  notify:
    - Restart Cyrus-Imapd service
  tags: cyrus-common
